"""Export the model sheets.

    python3 tools/characters/export.py

Writes src/js/content/characters.art.js (the grids the game draws from) and
tools/characters/art/<id>-<pose>.png at 1x, then asks LibreSprite to save an
.ase beside each PNG so the art can be hand-edited later. Edit the drawing
code in toma.py / kiyoshi.py, not the generated file.
"""
import json, os, subprocess, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import toma, kiyoshi  # noqa: E402

LS = "/Applications/LibreSprite.app/Contents/MacOS/libresprite"
# A shadow key and the base colour of the same region. The scorer treats a
# region's base colour painted on its shadow as a near miss, not a mistake.
SHADOW_OF = {"s": "S", "h": "H", "k": "K", "b": "B", "n": "N", "e": "E"}

CHARS = {
    "toma": (toma, {"front": toma.front, "side": toma.side, "bust": toma.bust}),
    "kiyoshi": (kiyoshi, {"front": kiyoshi.front, "side": kiyoshi.side, "bust": kiyoshi.bust}),
}


def main():
    out = {}
    os.makedirs(os.path.join(HERE, "art"), exist_ok=True)
    for cid, (mod, poses) in CHARS.items():
        used = set()
        entry = {"poses": {}}
        for pose, fn in poses.items():
            sp = fn()
            rows = sp.rows_text()
            used |= set("".join(rows)) - {"."}
            # the figure's own height: first to last row with anything in it
            filled = [y for y, r in enumerate(rows) if r.strip(".")]
            entry["poses"][pose] = {"w": sp.w, "h": sp.h, "top": filled[0], "bottom": filled[-1], "rows": rows}
            png = os.path.join(HERE, "art", f"{cid}-{pose}.png")
            im = Image.new("RGBA", (sp.w, sp.h), (0, 0, 0, 0))
            for y, r in enumerate(rows):
                for x, k in enumerate(r):
                    if k != ".":
                        c = mod.PAL[k]
                        im.putpixel((x, y), tuple(int(c[i:i + 2], 16) for i in (1, 3, 5)) + (255,))
            im.save(png)
            if os.path.exists(LS):
                subprocess.run([LS, "-b", png, "--save-as", png[:-4] + ".ase"], capture_output=True)
        entry["palette"] = {k: v for k, v in mod.PAL.items() if k in used}
        entry["shadowOf"] = {k: v for k, v in SHADOW_OF.items() if k in used and v in used}
        out[cid] = entry

    js = ('"use strict";\n'
          "/* GENERATED by tools/characters/export.py — do not edit by hand.\n"
          " * The Paper Moon Relay model sheets as pixel grids: one key per pixel,\n"
          " * '.' transparent, 'L' the shared line colour. Edit the drawing code in\n"
          " * tools/characters/*.py and re-run the exporter. */\n\n"
          "const CHARACTER_ART = " + json.dumps(out, indent=1) + ";\n\n"
          'if (typeof module !== "undefined") module.exports = CHARACTER_ART;\n')
    path = os.path.join(ROOT, "src", "js", "content", "characters.art.js")
    open(path, "w").write(js)
    for cid, e in out.items():
        print(cid, {p: (v["w"], v["h"], v["bottom"] - v["top"] + 1) for p, v in e["poses"].items()},
              len(e["palette"]), "colours")


if __name__ == "__main__":
    main()
