"use strict";

const CATS = [
  {
    id:"graphic", chrome:"dark", label:"Graphic Design", concept:"Ink under pressure",
    palette:["#E0442B","#F2ECE0","#14110E","#EFA845"],
    briefs:[
      { project:"SLOW PRESS", client:"Marrow & Co. — a letterpress shop going online after 60 years",
        ask:"They print by hand and they want the internet to feel the pressure. Build an identity that carries the bite of impression into flat pixels — something that looks like it dented the page.",
        deliver:["Wordmark plus three lockups","Poster series, three sheets at A1","Full business system","Motion signature, four seconds"],
        limits:["Two inks. No gradients.","Must survive a 12mm favicon.","One typeface — choose it and defend it."],
        tone:"Weighty · exact · slightly bruised" },
      { project:"TOTAL EXHAUST", client:"A city transit authority rebuilding after a procurement scandal",
        ask:"Trust is gone and the trains still run. Design a system that is relentlessly clear and refuses to be charming — the visual equivalent of an honest timetable.",
        deliver:["Signage grammar and arrow set","Wayfinding pictograms, eighteen","Ticket machine and app screens","Apology campaign, six sheets"],
        limits:["Legible at 40 metres and at arm’s length.","No stock photography of smiling commuters.","Palette must hold under sodium lighting."],
        tone:"Plain · durable · unembarrassed" },
      { project:"NIGHT MENU", client:"A 24-hour diner that only gets interesting after 2am",
        ask:"Same food all day, a completely different room at night. Make one identity that reads as breakfast in daylight and as something else entirely after midnight.",
        deliver:["Two-state identity system","Menu, working in both states","Neon spec and window vinyl","Matchbook"],
        limits:["One print run covers both states.","Hand-settable by a tired person at 4am.","No moon iconography."],
        tone:"Greasy · warm · faintly lawless" },
      { project:"HALF LIFE", client:"A deep geological repository that must warn people 100,000 years from now",
        ask:"Design a warning that survives the death of every language now spoken. It has to say danger to someone who shares nothing with you — no script, no symbols, no reason to trust the messenger — and it must not look like treasure worth digging for.",
        deliver:["Pictogram narrative, twelve panels","Monolith face system at three scales","Buried record-room plates","Specification for stone-cutters"],
        limits:["No text in any language.","Must read after two glaciations.","Nothing that could be mistaken for a monument to something valuable."],
        tone:"Grave \u00b7 wordless \u00b7 unmistakable" }
    ]
  },
  {
    id:"webui", chrome:"dark", label:"Interface Design", concept:"Panes of glass, suspended",
    palette:["#8FAFCB","#EDF3F8","#1E3A58","#4FD1C5"],
    briefs:[
      { project:"GLASSHOUSE", client:"A greenhouse monitor for people who keep killing plants",
        ask:"Six sensors, one anxious owner. Turn raw telemetry into a single honest feeling: fine, or not fine. Everything else is secondary.",
        deliver:["Dashboard at three breakpoints","Five alert states","Onboarding, four screens","Empty and failure states"],
        limits:["The home screen answers the question in under two seconds.","No numbers above the fold.","Usable one-handed in a dark room."],
        tone:"Calm · certain · quietly alive" },
      { project:"THE LEDGER", client:"A cooperative bank owned by its 900 members",
        ask:"Every member can see where the money goes. Design the interface for radical financial transparency without producing a spreadsheet nobody opens.",
        deliver:["Public ledger view","Member vote flow","Statement redesign","Design tokens and documentation"],
        limits:["WCAG AAA on every text pair.","Cancel carries the same weight as confirm.","Runs on a five-year-old Android."],
        tone:"Open · unglamorous · trustworthy" },
      { project:"REPEATER", client:"A practice tool built by a drummer who got tired of scrubbing",
        ask:"Looping a four-second passage three hundred times is the entire product. Design around repetition — the controls should recede as the player improves.",
        deliver:["Player and loop selector","Progressive disclosure spec","Session history view","Watch companion"],
        limits:["Core loop reachable in one gesture.","Nothing that requires looking down mid-play.","Twelve milliseconds to visual feedback."],
        tone:"Tight · rhythmic · out of the way" },
      { project:"NIGHT SHIFT", client:"A shift-swapping tool used by hospital staff mid-shift",
        ask:"Four in the morning, one hand, a corridor, someone else\u2019s emergency two doors down. Design the swap flow for a person whose attention you are borrowing, not buying.",
        deliver:["Swap flow, one-handed","True dark mode","Interrupted-and-resumed states","Ward manager batch approval"],
        limits:["Every target reachable by one thumb, gloved.","No notification may fire between 23:00 and 07:00.","Any flow survives being abandoned for an hour."],
        tone:"Quiet \u00b7 reachable \u00b7 forgiving" }
    ]
  },
  {
    id:"asset3d", chrome:"dark", label:"3D & Asset", concept:"Mass, and one light",
    palette:["#8A8279","#F0EAE1","#2A251F","#B8683A"],
    briefs:[
      { project:"QUARRY", client:"An open-world game set in an abandoned marble quarry",
        ask:"Build the hero prop: a stone-cutting machine, rusted in place for forty years. It must read as dangerous from fifty metres and as pitiable up close.",
        deliver:["High-res and game-res mesh","4K PBR material set","Three LODs","Damaged variant"],
        limits:["42k triangles at LOD0.","One material slot. No emissive.","Silhouette must read at 32 pixels."],
        tone:"Heavy · abandoned · still sharp" },
      { project:"SOFT SERVICE", client:"A furniture brand that sells only online",
        ask:"The sofa has to be believed before it is ever touched. Model and shade one piece convincingly enough that the return rate drops.",
        deliver:["Configurable model, six fabrics","Studio and room lighting sets","Turntable, 360 frames","AR-ready GLB under 8MB"],
        limits:["Fabric must survive extreme close-up.","No compositing tricks — it renders live.","One asset serves print and web."],
        tone:"Tactile · honest · expensive" },
      { project:"CARRIER", client:"A hard science-fiction short: one shot, six minutes",
        ask:"A cargo hauler docks with nothing. Design and build the ship so its function is legible without a single line of dialogue.",
        deliver:["Full exterior and dock module","Blockout for previs","Shot-ready shaders","Wear and decal pass"],
        limits:["Every surface justifies itself mechanically.","No red glowing anything.","Scale must read against a human at 200 metres."],
        tone:"Functional · cold · enormous" },
      { project:"THE SPECIMEN", client:"A museum whose blue whale has not fitted in its hall since 1974",
        ask:"Twenty-six metres of articulated skeleton, a nineteen-metre room, and 168 bones that must not be touched. Digitise her so she can be seen at true scale again \u2014 and so a researcher never has to open the crate.",
        deliver:["Full articulation at 0.4 mm","Decimated viewing model under 100 MB","Reconstruction pass, colour-separated","Element register, all 168"],
        limits:["Every replica bone marked in a distinct colour \u2014 nothing invented is hidden.","Scale bar in every capture.","CC0. It leaves with no conditions attached."],
        tone:"Exact \u00b7 enormous \u00b7 unsentimental" }
    ]
  },
  {
    id:"illustrative", chrome:"dark", label:"Illustration", concept:"Pigment finding water",
    palette:["#2E3A8C","#C4643F","#B24A6E","#FBF6EA"],
    briefs:[
      { project:"FIELD GUIDE TO NOTHING", client:"A small press publishing a guide to vacant lots",
        ask:"Forty-two species that only grow where buildings fell. Illustrate them with the seriousness of a Victorian botanical plate and none of the nostalgia.",
        deliver:["Forty-two plates","Cover and endpapers","Six chapter openers","Twenty spot marks"],
        limits:["Two spot colours plus black.","Botanically accurate — it will be checked.","No decorative frames."],
        tone:"Precise · unsentimental · slightly weedy" },
      { project:"THE LONG QUIET", client:"An album about a winter spent alone",
        ask:"Nine tracks, one continuous image that can be cropped nine ways. Make the solitude feel chosen rather than inflicted.",
        deliver:["Master artwork at 3:1","Nine crops","Vinyl gatefold","Animated loop, eight seconds"],
        limits:["No human figures.","Must survive a 300px thumbnail.","One light source."],
        tone:"Cold · spacious · almost warm" },
      { project:"MARGIN NOTES", client:"A 900-page legal history nobody will finish",
        ask:"Illustrate the margins, not the text. Give a reader who is drifting a reason to keep turning pages.",
        deliver:["One hundred and twenty marginalia","Fourteen full-page interludes","Cover","Reading-ribbon art"],
        limits:["Line art only — print is one colour.","Nothing that mocks the subject.","Must work upside down at a glance."],
        tone:"Dry · witty · patient" },
      { project:"TIDE TABLES", client:"A working almanac that goes to sea in a wheelhouse",
        ask:"Forty-two plates that are working diagrams first and drawings second. Somebody will hold this open one-handed in a wind and use the page itself to measure a shellfish. Draw for that.",
        deliver:["Shellfish plates at 1:1","Harbour light sequences","Working knots, twelve","Estuary chart, redrawn"],
        limits:["One colour. Black.","Legal minimum sizes drawn at true scale.","No weathered fishermen, no sunsets, no gulls."],
        tone:"Working \u00b7 plain \u00b7 durable" }
    ]
  },
  {
    id:"character", chrome:"light", label:"Character Design", concept:"Someone arriving",
    palette:["#FFB656","#7A4A1C","#160E07","#E8C9A0"],
    briefs:[
      { project:"THE UNDERSTUDY", client:"An animated feature about a stage double who never goes on",
        ask:"Design a protagonist built to be overlooked — then find the two details that make an audience unable to stop watching them.",
        deliver:["Turnaround and expression sheet","Three costume states","Hands and silhouette study","Model sheet for a crew of forty"],
        limits:["Must read at 8% of frame height.","No accessories that can be removed.","Appeal without cuteness."],
        tone:"Muted · watchful · quietly magnetic" },
      { project:"SALVAGE CREW", client:"A co-op game for four players sharing one oxygen supply",
        ask:"Four characters who stay distinguishable in a dark corridor at thirty frames per second. Difference is the entire design problem.",
        deliver:["Four full designs","Silhouette separation sheet","Palette separation study","Damaged-state variants"],
        limits:["Distinct at 5% opacity, black on black.","Same skeleton for all four.","No colour-only differentiation."],
        tone:"Grimy · specific · functional" },
      { project:"THE GOOD NEIGHBOUR", client:"A children’s series about something very large trying not to break anything",
        ask:"Eleven feet tall and terrified of doing damage. Design it so a five-year-old sees a friend and an adult sees the anxiety.",
        deliver:["Character design and scale chart","Expression range, twenty-four","Two supporting cast","Plush viability study"],
        limits:["No teeth in the neutral pose.","Drawable by thirty different hands.","Readable when 90% offscreen."],
        tone:"Enormous · gentle · apologetic" },
      { project:"THE INTERPRETER", client:"A broadcaster building a signing avatar for overnight bulletins",
        ask:"The hands carry the words and the face carries the grammar \u2014 tense, negation, question. Design a figure that reads as language rather than gesture, at one-sixth of frame height, to people who will know immediately if you have faked it.",
        deliver:["Figure design for the signing window","Handshape sheet, full inventory","Grammatical expression range","Neutral pose study"],
        limits:["Legible at 1/6 frame height at broadcast bitrate.","Neutral face must read as nothing \u2014 not bored, not friendly.","Mouth patterns must not read as lip-sync."],
        tone:"Legible \u00b7 grammatical \u00b7 unperformed" }
    ]
  },
  {
    id:"motion", chrome:"light", label:"Motion Design", concept:"Light writing itself",
    palette:["#57E0FF","#FF5FA8","#FFE08A","#070C11"],
    briefs:[
      { project:"COLD OPEN", client:"A documentary series on weather forecasting before satellites",
        ask:"Sixteen seconds before the first word is spoken. Build a title sequence out of data alone — barometric charts, ship logs, hand-drawn isobars — that earns the show its dread.",
        deliver:["Sixteen-second main title","Six lower thirds","Transition kit","End card"],
        limits:["No 3D — everything must feel printed.","Works muted.","Type appears once and stays."],
        tone:"Analog · mounting · exact" },
      { project:"HANDOFF", client:"A payments company explaining something genuinely boring",
        ask:"Ninety seconds on settlement timing, for people who do not care. Motion is the only reason anyone stays to the end.",
        deliver:["Ninety-second explainer","Five social loops","Icon animation library","Eight style frames"],
        limits:["No voiceover.","One continuous camera move.","Must render as Lottie."],
        tone:"Brisk · clear · lightly funny" },
      { project:"STANDING WAVE", client:"Concert visuals for a forty-minute drone piece",
        ask:"One idea, forty minutes, no cuts. Build a system that rewards a listener who never looks away and forgives one who does.",
        deliver:["Generative visual system","Three movement states","Failsafe pre-render","Operator controls"],
        limits:["Live at 60fps on one laptop.","No beat detection — there is no beat.","Must never visibly loop."],
        tone:"Slow · immense · hypnotic" },
      { project:"BLACK BOX", client:"An air accident investigation branch, for a published report",
        ask:"Render recorder data as a sequence a grieving family can watch and an engineer can check. Everything you add that is not in the data is a lie, and everything you make exciting is a cruelty.",
        deliver:["Reconstruction to the last data point","Uncertainty treatment","Parameter overlay system","Figure-scale version for the report"],
        limits:["No sound of any kind.","Impact is never depicted.","No people, no silhouettes, no cockpit occupants."],
        tone:"Flat \u00b7 exact \u00b7 merciful" }
    ]
  },
  {
    id:"type", chrome:"light", label:"Type Design", concept:"The chisel and the counter",
    palette:["#F4F1E9","#D3452F","#5ED6D6","#272D31"],
    briefs:[
      { project:"COUNTERWEIGHT", client:"A newspaper returning to print, weekly",
        ask:"Design a text face for people who chose paper on purpose. It should feel inevitable — as though news always looked this way.",
        deliver:["Text roman and italic","Bold and display cut","Three headline optical sizes","Spec and proof book"],
        limits:["8.4pt on newsprint is the test.","Four styles. No superfamily.","Must set a fourteen-word headline in one line."],
        tone:"Sober · warm · load-bearing" },
      { project:"SIGNAL WORK", client:"A wayfinding face for an airport that never closes",
        ask:"Every glyph will be read by someone exhausted, in a hurry, in their second language. Design for the worst possible reading conditions.",
        deliver:["Regular and medium","Numerals and arrow set","Multi-script pilot: Latin, Arabic","Spacing specification"],
        limits:["Tested at a 3° viewing angle.","Zero ambiguous pairs — I, l, 1, O, 0.","Backlit and front-lit weights must match."],
        tone:"Neutral · relentless · kind" },
      { project:"SHOWCARD", client:"A revival of one sign-painter’s alphabet, from eleven photographs",
        ask:"Eleven blurry photos of one man’s brushwork from 1954. Build a working typeface that keeps the hand and loses the accident.",
        deliver:["Display face, one weight","Forty alternates and ligatures","Catalogue specimen","Historical note"],
        limits:["Every decision documented against a source photo.","No smoothing of intentional irregularity.","Must set words he never painted."],
        tone:"Hand-made · confident · revived" },
      { project:"THE PRESCRIPTION", client:"A medical packaging firm where a misread number is a dosing error",
        ask:"Set 5.5 point on reflective blister foil, read at three in the morning without glasses. One misreading of a strength or a name in two hundred and forty and the face is rejected.",
        deliver:["Text face, two weights","Lining and tabular figures","Tall Man capital set","Legibility panel report"],
        limits:["1, l and I unmistakable at 5.5 pt.","Tested on foil, not on paper.","Colour may never be the only difference between two strengths."],
        tone:"Unambiguous \u00b7 sober \u00b7 load-bearing" }
    ]
  }
];
