"use strict";
/* ── the suite's icons ────────────────────────────────────
 * Modes, tools, layers, drawers and page blocks, in the same 16 × 16 pixel
 * format as everything in icons.js. Their ink is currentColor and their paper
 * a CSS variable (--ico-paper), so one icon reads on the suite's dark look
 * and on its light one; the colours in them stay put.
 */
Object.assign(ICON_ART, {
  "mode-vector":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................",".....kkkkk......",".....kwwwk......","....kkkkkkk.....","...kaaaaaaak....","...kaaaaaaak....","..kaaaakaaaak...","..kaaaakaaaak...",
    "..kaaaakaaaak...","...kaaakaaak....","...kaaakaaak....","....kaakaak.....","....kaakaak.....",".....kakak......","......kkk.......",".......k........"]},
  "mode-pixel":{p:{p:"#FF5FA8",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","...pppp..pppp...","...pppp..pppp...",".ppwwpppppppppp.",".ppwwpppppppppp.",".pppppppppppppp.",".pppppppppppppp.",
    "...pppppppppp...","...pppppppppp...",".....pppppp.....",".....pppppp.....",".......pp.......",".......pp.......","................","................"]},
  "mode-layout":{p:{a:"#3FA7E8",k:"currentColor",m:"var(--ico-mid,#8A8A96)",w:"var(--ico-paper,#FFFFFF)",y:"#F2C94C"},g:[
    "................","..kkkkkkkkkkkk..","..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kwwwwwwwwwwk..","..kwmmmmmmmmwk..","..kwwwwwwwwwwk..",
    "..kwmmmmmmwwwk..","..kwwwwwwwwwwk..","..kwyyyywmmmwk..","..kwyyyywwwwwk..","..kwyyyywmmmwk..","..kwwwwwwwwwwk..","..kkkkkkkkkkkk..","................"]},
  "t-node":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","................","................","................","......kkkk......",".aa...kwwk...aa.",".aaaaakwwkaaaaa.",
    "...kk.kkkk.kk...","..kk........kk..","..k..........k..","..k..........k..",".kk...........k.",".k............k.",".k............k.","................"]},
  "t-polygon":{p:{g:"#4FC27A",k:"currentColor"},g:[
    "................",".......kk.......",".....kkggkk.....","...kkggggggkk...","..kggggggggggk..","..kggggggggggk..","..kggggggggggk..","..kggggggggggk..",
    "..kggggggggggk..","..kggggggggggk..","..kggggggggggk..","..kkgggggggg.k..","....kkgggg.kk...","......kk.kk.....","........k.......","................"]},
  "t-star":{p:{k:"currentColor",y:"#F2C94C"},g:[
    "................",".......yk.......",".......yk.......",".......kk.......","......ykyk......","......kyyk......",".kkkkkkyykkkkkk.","..kkyyyyyyyy.k..",
    "....kyyyyyykk...",".....kyyyyk.....","....ykyyyyk.....","....kyy.kyyk....","....kykk.kkk....","...kkk.....kk...","...k........k...","................"]},
  "t-line":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................","...........kkkk.","...........kaak.","...........kaak.","...........kkkk.","..........kk....",".........kk.....","........kk......",
    ".......kk.......","......kk........",".....kk.........",".kkkkk..........",".kaak...........",".kaak...........",".kkkk...........","................"]},
  "t-hand":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","......kk........","...kkkwwkkk.....","..kwwkwwkwwkkk..","..kwwkwwkwwkwwk.","..kwwkwwkwwkwwk.","..kwwkwwkwwkwwk.","kk.kwwkwwkwwkwwk",
    "kwkkwwwwwwwwwwk.",".kwkwwwwwwwwwwk.","..kwwwwwwwwwwwk.","..kwwwwwwwwwwwk.","...kwwwwwwwwwk..","....kwwwwwwwk...","....kkkkkkkkk...","................"]},
  "t-textpath":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................","................",".....kkkkkk.....",".....kkkkkk.....",".......kk.......",".......kk.......",".......kk.......","......kkkk......",
    "....aaa..aaa....","...aa......aa...","...a........a...","..a..........a..",".aa..........aa.",".a............a.",".a............a.","................"]},
  "t-italic":{p:{k:"currentColor"},g:[
    "................","................","......kkkkkk....","......kkkkkk....","........kk......","........kk......",".......kk.......",".......kk.......",
    ".......kk.......","......kk........","......kk........",".....kk.........","...kkkkkk.......","...kkkkkk.......","................","................"]},
  "t-marquee":{p:{k:"currentColor"},g:[
    "................","................","..kk.kk.kk.kkk..","..k..........k..","................","..k..........k..","..k..........k..","................",
    "..k..........k..","..k..........k..","................","..k..........k..","..k..........k..","..kk.kk.kk.kk...","................","................"]},
  "f-rect":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................","................","................","..kkkkkkkkkkkk..","..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kaaaaaaaaaak..",
    "..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kaaaaaaaaaak..","..kkkkkkkkkkkk..","................","................","................"]},
  "f-ellipse":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................","................",".....kkkkkk.....","...kkaaaaaakk...","..kaaaaaaaaaak..","..kaaaaaaaaaak..",".kaaaaaaaaaaaak.",".kaaaaaaaaaaaak.",
    ".kaaaaaaaaaaaak.",".kaaaaaaaaaaaak.","..kaaaaaaaaaak..","..kaaaaaaaaaak..","...kkaaaaaakk...",".....kkkkkk.....","................","................"]},
  "ta-left":{p:{k:"currentColor"},g:[
    "................","................","................","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................","..kkkkkkkk......","..kkkkkkkk......",
    "................","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................","..kkkkkk........","..kkkkkk........","................","................"]},
  "ta-center":{p:{k:"currentColor"},g:[
    "................","................","................","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................","....kkkkkkkk....","....kkkkkkkk....",
    "................","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................",".....kkkkkk.....",".....kkkkkk.....","................","................"]},
  "ta-right":{p:{k:"currentColor"},g:[
    "................","................","................","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................","......kkkkkkkk..","......kkkkkkkk..",
    "................","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................","........kkkkkk..","........kkkkkk..","................","................"]},
  "eye":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","................","................","......kkkk......","...kkkkkkkkkk...","..kk.kwaaak.kk..",".kk..kakkak..kk.",
    ".k...kakkak...k.",".kk..kaaaak..kk.","..kk..kkkk..kk..","...kkkk..kkkk...","......kkkk......","................","................","................"]},
  "eye-off":{p:{m:"var(--ico-mid,#8A8A96)"},g:[
    "................","................","................","................","................","................","................","................",
    ".m............m.",".mm..........mm.","...mm......mm...","...m.mmmmmm.m...","..m....m.....m..",".m.....m......m.",".......m........","................"]},
  "lock":{p:{k:"currentColor",y:"#F2C94C"},g:[
    "................","................","......kkkk......",".....k....k.....",".....k....k.....",".....k....k.....",".....k....k.....","...kkkkkkkkkk...",
    "...kyyyyyyyyk...","...kyyykkyyyk...","...kyyykkyyyk...","...kyyykkyyyk...","...kyyykkyyyk...","...kyyyyyyyyk...","...kkkkkkkkkk...","................"]},
  "unlock":{p:{m:"var(--ico-mid,#8A8A96)"},g:[
    "................","................",".........mmmm...","........m....m..","........m....m..","........m....m..","........m.......",".mmmmmmmmmm.....",
    ".m........m.....",".m........m.....",".m...mm...m.....",".m...mm...m.....",".m........m.....",".m........m.....",".mmmmmmmmmm.....","................"]},
  "l-dup":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................",".kkkkkkkkk......",".kwwwwwwwk......",".kwwwwwwwk......",".kwwwwwwwk......",".kwwwwwwwk......",".kwwwwkkkkkkkkk.",".kwwwwkaaaaaaak.",
    ".kwwwwkaaaaaaak.",".kkkkkkaaaaaaak.","......kaaaaaaak.","......kaaaaaaak.","......kaaaaaaak.","......kaaaaaaak.","......kkkkkkkkk.","................"]},
  "l-up":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................",".......ak.......","......akak......",".....kkaaak.....","....kaaaaaak....","...kaaaaaaaak...","..kkkkaaaakkkk..","......kaak......",
    "......kaak......","..kkkkkkkkkkkk..","..kwwwwwwwwwwk..","..kwwwwwwwwwwk..","..kwwwwwwwwwwk..","..kkkkkkkkkkkk..","................","................"]},
  "l-down":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","..kkkkkkkkkkkk..","..kwwwwwwwwwwk..","..kwwwwwwwwwwk..","..kwwwwwwwwwwk..","..kkkkkkkkkkkk..","......kaak......",
    "......kaak......","..kkkkaaaakkkk..","...kaaaaaaa.k...","....kaaaaa.k....",".....kkaa.k.....","......ak.k......","........k.......","................"]},
  "l-del":{p:{k:"currentColor",r:"#E8563B",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","......kkkk......","......kkkk......","..kkkkkkkkkkkk..","...kkkkkkkkkk...","...kwwwwwwwwk...","...kwrwrrwrwk...","...kwrwrrwrwk...",
    "...kwrwrrwrwk...","...kwrwrrwrwk...","...kwrwrrwrwk...","...kwrwrrwrwk...","...kwrwrrwrwk...","...kwwwwwwwwk...","...kkkkkkkkkk...","................"]},
  "mirror":{p:{k:"currentColor",p:"#FF5FA8",w:"var(--ico-paper,#FFFFFF)"},g:[
    ".......pp.......",".......pp.......","................","......kppwk.....",".....kkppwk.....","....kkk..wkk....","....k.kppwkk....","...kk.kppwkwk...",
    "...kk.k..wkwk...","..kkk.kppwkwwk..",".kkkk.kppwkwwk..",".kkkk.k..wkwwwk.","kkkkkkkpp.kkkkk.",".......pp.......","................",".......pp......."]},
  "mirror-h":{p:{k:"currentColor",p:"#FF5FA8",w:"var(--ico-paper,#FFFFFF)"},g:[
    "............k...","..........kkk...",".........kkkk...",".......kkkkkk...",".....kkkkkkkk...","....kk......k...","...kkkkkkkkkk...","pp.pp.pp.pp.pp.p",
    "pp.pp.pp.pp.pp.p","...wwwwwwwww....","...kkkkkkkkkk...",".....kkwwwwwk...",".......kkwwwk...",".........kkwk...","...........kk...","................"]},
  "flip-h":{p:{a:"#3FA7E8",k:"currentColor",m:"var(--ico-mid,#8A8A96)"},g:[
    "................",".......mm.......",".......mm.......",".......mm.......","....ak.mm.k.....","...akk.mm.kk....","..akak.mm.kak...",".akaak.mm.kaak..",
    ".kaaak.mm.kaa.k.","..kaak.mm.ka.k..","...kak.mm.k.k...","....kk.mm.kk....",".....k.mm.k.....",".......mm.......",".......mm.......","................"]},
  "flip-v":{p:{a:"#3FA7E8",k:"currentColor",m:"var(--ico-mid,#8A8A96)"},g:[
    "................",".......ak.......","......akak......",".....akaaak.....","....akaaaaak....","....kkkkkkkkk...","................",".mmmmmmmmmmmmmm.",
    ".mmmmmmmmmmmmmm.","................","...akkkkkkkkk...","....akaaaa.k....",".....akaa.k.....","......ak.k......","........k.......","................"]},
  "grid":{p:{o:"#FFA040"},g:[
    "................",".oooooooooooooo.",".o...o....o...o.",".o...o....o...o.",".o...o....o...o.",".oooooooooooooo.",".o...oooooo...o.",".o...oooooo...o.",
    ".o...oooooo...o.",".o...oooooo...o.",".oooooooooooooo.",".o...o....o...o.",".o...o....o...o.",".o...o....o...o.",".oooooooooooooo.","................"]},
  "smart":{p:{k:"currentColor",p:"#FF5FA8",w:"var(--ico-paper,#FFFFFF)"},g:[
    "........p.......","........p.......","........p.......","........p.......","ppppkkkkkkkkpppp","....kwwwpwwk....","....kwwwpwwk....","....kwwwpwwk....",
    "....kwwwpwwk....","....kwwwpwwk....","....kwwwpwwk....","....kkkkkkkk....","........p.......","........p.......","........p.......","........p......."]},
  "snap":{p:{k:"currentColor",r:"#E8563B",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","..kkkk....kkkk..","..krrk....krrk..","..krrk....krrk..","..krrk....krrk..","..krrk....krrk..","..krrk....krrk..","..krrkkkkkkrrk..",
    "..krrrrrrrrrrk..","...krrrrrrrrk...","....kkkkkkkk....","................","..ww.......ww...","..ww.......ww...","................","................"]},
  "guides-x":{p:{r:"#E8563B",t:"#3FD3FF"},g:[
    "....t...........","....t...........","................","................","tt..tt..tt..tt..","....t...........","................","................",
    "....t...rr...rr.","....t....rr.rr..","..........rrr...","..........rrr...","....t....rr.rr..","....t...rr...rr.","........r.....r.","................"]},
  "none":{p:{k:"currentColor",r:"#E8563B",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","......kkkk......","....kkwwwwkk....","...kwwwwwwwrr...","...kwwwwwwrrk...","..kwwwwwwrrwwk..","..kwwwwwrrwwwk..",
    "..kwwwwrrwwwwk..","..kwwwrrwwwwwk..","...kwrrwwwwwk...","...krrwwwwwwk...","....rkwwwwkk....","......kkkk......","................","................"]},
  "plus":{p:{k:"currentColor"},g:[
    "................","................",".......kk.......",".......kk.......",".......kk.......",".......kk.......",".......kk.......","..kkkkkkkkkkkk..",
    "..kkkkkkkkkkkk..",".......kk.......",".......kk.......",".......kk.......",".......kk.......",".......kk.......","................","................"]},
  "al-left":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    ".a..............",".a..............",".a..............",".akkkkkkkkkk....",".akwwwwwwwwk....",".akwwwwwwwwk....",".akkkkkkkkkk....",".a..............",
    ".a..............",".akkkkkk........",".akwwwwk........",".akwwwwk........",".akkkkkk........",".a..............",".a..............",".a.............."]},
  "al-hcenter":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    ".......a........",".......a........",".......a........","...kkkkkkkkkk...","...kwwwwwwwwk...","...kwwwwwwwwk...","...kkkkkkkkkk...",".......a........",
    ".......a........",".....kkkkkk.....",".....kwwwwk.....",".....kwwwwk.....",".....kkkkkk.....",".......a........",".......a........",".......a........"]},
  "al-right":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "..............a.","..............a.","..............a.","....kkkkkkkkkka.","....kwwwwwwwwka.","....kwwwwwwwwka.","....kkkkkkkkkka.","..............a.",
    "..............a.","........kkkkkka.","........kwwwwka.","........kwwwwka.","........kkkkkka.","..............a.","..............a.","..............a."]},
  "al-top":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","aaaaaaaaaaaaaaaa","...kkkk..kkkk...","...kwwk..kwwk...","...kwwk..kwwk...","...kwwk..kwwk...","...kwwk..kwwk...","...kwwk..kkkk...",
    "...kwwk.........","...kwwk.........","...kwwk.........","...kkkk.........","................","................","................","................"]},
  "al-vcenter":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","................","...kkkk.........","...kwwk.........","...kwwk..kkkk...","...kwwk..kwwk...","aaakwwkaakwwkaaa",
    "...kwwk..kwwk...","...kwwk..kwwk...","...kwwk..kkkk...","...kwwk.........","...kkkk.........","................","................","................"]},
  "al-bottom":{p:{a:"#3FA7E8",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","................","................","...kkkk.........","...kwwk.........","...kwwk.........","...kwwk.........",
    "...kwwk..kkkk...","...kwwk..kwwk...","...kwwk..kwwk...","...kwwk..kwwk...","...kwwk..kwwk...","...kkkk..kkkk...","aaaaaaaaaaaaaaaa","................"]},
  "n-corner":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................","................","................","......kkkk......","......kaak......","......kaak......","......kkkk......","......k..k......",
    ".....k....k.....","....k......k....","....k......k....","...k........k...","..k..........k..","..k..........k..",".k............k.","................"]},
  "n-smooth":{p:{a:"#3FA7E8",k:"currentColor",m:"var(--ico-mid,#8A8A96)"},g:[
    "................","................","................","......kkkk......","mm....kaak...mm.","mmmmmmkaakmmmmm.","....kkkkkkkk....","...k........k...",
    "..kk........kk..","..k..........k..","..k..........k..",".kk..........kk.",".k............k.",".k............k.",".k............k.","................"]},
  "n-sym":{p:{a:"#3FA7E8",k:"currentColor",p:"#FF5FA8"},g:[
    "................","................","................","......kkkk......","pp....kaak....pp","ppppppkaakpppppp","....kkkkkkkk....","...k........k...",
    "..kk........kk..","..k..........k..","..k..........k..",".kk..........kk.",".k............k.",".k............k.",".k............k.","................"]},
  "f-new":{p:{g:"#4FC27A",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","..kkkkkkkkk.....","..kwwwwwwwkk....","..kwwwwwwwkwk...","..kwwwwwwwkkkk..","..kwwwwwwwwwwk..","..kwwwwwwwwwwk..","..kwwwwggwwwwk..",
    "..kwwwwggwwwwk..","..kwwggggggwwk..","..kwwggggggwwk..","..kwwwwggwwwwk..","..kwwwwggwwwwk..","..kwwwwwwwwwwk..","..kkkkkkkkkkkk..","................"]},
  "f-undo":{p:{k:"currentColor"},g:[
    "................","......k.........","....kkk.........","...kkkk.........","..kkkkk.........","kkkkkkkkkkk.....","k.kkkkkkkkkk....",".kkkkkk...kkk...",
    "...kkkk....kk...","....kkk....kk...","......k....kk...","..........kk....",".........kkk....",".........kk.....","................","................"]},
  "f-redo":{p:{k:"currentColor"},g:[
    "................",".........k......",".........kk.....",".........kkkk...",".........kkkkk..",".....kkkkkkkkkk.","....kkkkkkkkkk.k","...kkk...kkk.kk.",
    "...kk....kk.k...","...kk....kkk....","...kk....k......","....kk..........","....kkk.........",".....kk.........","................","................"]},
  "f-save":{p:{a:"#3FA7E8",k:"currentColor",m:"var(--ico-mid,#8A8A96)",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................",".kkkkkkkkkkkkk..",".kaawwwwwwwwaak.",".kaawwwwwkkwaak.",".kaawwwwwkkwaak.",".kaawwwwwkkwaak.",".kaawwwwwwwwaak.",".kaaaaaaaaaaaak.",
    ".kaaaaaaaaaaaak.",".kakkkkkkkkkkak.",".kawwwwwwwwwwak.",".kawwmmmmmmwwak.",".kawwwwwwwwwwak.",".kawwmmmmmmwwak.","..kwwwwwwwwwwkk.","................"]},
  "f-export":{p:{g:"#4FC27A",k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","..........ggggg.","..........ggggg.","............ggg.","...........gggg.",".kkkkkkkkkgg.gg.",".kwwwwwwwgg.....",".kwwwwwwggk.....",
    ".kwwwwwggwk.....",".kwwwwggwwk.....",".kwwwwwwwwk.....",".kwwwwwwwwk.....",".kwwwwwwwwk.....",".kwwwwwwwwk.....",".kkkkkkkkkk.....","................"]},
  "f-deliver":{p:{k:"currentColor",m:"var(--ico-mid,#8A8A96)",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................",".............kk.","...........kkkk.",".........kkwkk..","......wkkwwkwk..","....wkkwwwwkk...","..wkkwwwwwkwk...",".kkwwwwwwkw.k...",
    "...kkkwwkwwk....","......kmwwwk....",".......kww.k....","........kwk.....","........mwk.....",".........k......",".........k......","................"]},
  "f-import":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................",".......aa.......",".......aa.......",".......aa.......",".......aa.......",".......aa.......",".......aa.......","...aaaaaaaaa....",
    "...kkkkkkkkkk...",".k..kaaaaa.k..k.",".k...kkaa.k...k.",".k.....k.k....k.",".k......k.....k.",".k............k.",".kkkkkkkkkkkkkk.","................"]},
  "f-down":{p:{g:"#4FC27A",k:"currentColor"},g:[
    "................","......gggg......","......gggg......","......gggg......","......gggg......","......gggg......","..kkkkkkkkkkk...","...kgggggggk....",
    "....kggggggk....",".....kggggk.....",".k....kggk....k.",".k.....k.k....k.",".k......k.....k.",".k............k.",".kkkkkkkkkkkkkk.","................"]},
  "z-in":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","....kkkk........","..kkwwwwkk......","..kwwkkwwk......",".kwwwkkwwwk.....",".kwkkkkkkwk.....",".kwkkkkkkwk.....",".kwwwkkwwwk.....",
    "..kwwkkwwk......","..kkwwwwkkk.....","....kkkk.kkk....","..........kkk...","...........kkk..","............kkk.",".............kk.","................"]},
  "z-out":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","....kkkk........","..kkwwwwkk......","..kwwwwwwk......",".kwwwwwwwwk.....",".kwkkkkkkwk.....",".kwkkkkkkwk.....",".kwwwwwwwwk.....",
    "..kwwwwwwk......","..kkwwwwkkk.....","....kkkk.kkk....","..........kkk...","...........kkk..","............kkk.",".............kk.","................"]},
  "z-fit":{p:{a:"#3FA7E8",k:"currentColor"},g:[
    "................",".kkkk......kkkk.",".k............k.",".k............k.",".k............k.",".....kkkkkk.....",".....kaaaak.....",".....kaaaak.....",
    ".....kaaaak.....",".....kaaaak.....",".....kkkkkk.....",".k............k.",".k............k.",".k............k.",".kkkk......kkkk.","................"]},
  "card":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)",y:"#F2C94C"},g:[
    "................","....kkkkkkkkkkk.","....kwwwwwwwwwk.","....kwwwwwwwwwk.",".kkkkkkkkkkkwwk.",".kyyyyyyyyykwwk.",".kyyyyyyyyykwwk.",".kykkkkkkkykwwk.",
    ".kyyyyyyyyykwwk.",".kykkkkkyyykwwk.",".kyyyyyyyyykwwk.",".kyyyyyyyyykkkk.",".kyyyyyyyyyk....",".kyyyyyyyyyk....",".kkkkkkkkkkk....","................"]},
  "tuck":{p:{k:"currentColor"},g:[
    "................","................","................","................","................","................",".......kk.......","......kkkk......",
    ".....kk..kk.....","....kk....kk....","...kk......kk...","...k........k...","................","................","................","................"]},
  "c-wand":{p:{k:"currentColor",y:"#F2C94C"},g:[
    "................","............y...","......y....yyy..","............y...","................",".........yyy....",".........yyy..y.","........kyyy....",
    ".......kkk......","......kkk...y...",".....kkk........","....kkk.........","...kkk..........","..kkk...........","..kk............","................"]},
  "c-lasso":{p:{k:"currentColor",p:"#FF5FA8"},g:[
    "................","......kkkkk.....","....kk.....kk...","...k.........k..","..k...........k.","..k...........k.","..k...........k.","...k.........k..",
    "....kk.....kk...","...kk.kkkkk.....","...k............","...kk...........","....kp..........","....p...........","....k...........","....k..........."]},
  "c-invert":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","..kkkkkkkkkkkk..","..kwwwwwwwwkkk..","..kwwwwwwwkkkk..","..kwwwwwwkkkkk..","..kwwwwwkkkkkk..","..kwwwwkkkkkkk..",
    "..kwwwkkkkkkkk..","..kwwkkkkkkkkk..","..kwkkkkkkkkkk..","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","..kkkkkkkkkkkk..","................","................"]},
  "c-replace":{p:{a:"#3FA7E8",g:"#4FC27A",k:"currentColor",w:"var(--ico-paper,#FFFFFF)",y:"#F2C94C"},g:[
    "................","................","................",".kkkkkkkkkk.....",".kwwwwwwwwk.a...",".kwwwwyywwk.a...",".kwwwwyywwk.a...",".kwwwwwwwwk.a...",
    ".kwwwwwwwwk.a...",".kggggggggk.a...",".kggggggggaaaa..",".kggggggggkaa...",".kkkkkkkkkkaa...","................","................","................"]},
  "d-swatch":{p:{g:"#4FC27A",k:"currentColor",p:"#FF5FA8",r:"#E8563B",t:"#3FD3FF",w:"var(--ico-paper,#FFFFFF)",y:"#F2C94C"},g:[
    "................","....kkkkkk......","..kkwwwwwwkk....",".kwwrrwwyywwk...",".kwwrrwwyywwwk..","kwwwwwwwwwwggk..","kwttwwwwwwwggk..","kwttwwwwwwwwk...",
    "kwwwwwwwkkkk....","kwppwwwk........","kwppwwwk........",".kwwwwwk........","..kkwwwwk.......","....kkkkk.......","................","................"]},
  "blk-lede":{p:{k:"currentColor",m:"var(--ico-mid,#8A8A96)"},g:[
    "................","................","................","................",".kkkkkkkkkkkkkk.",".kkkkkkkkkkkkkk.",".kkkkkkkkkkkkkk.","................",
    ".kkkkkkkkkk.....",".kkkkkkkkkk.....",".kkkkkkkkkk.....","................","................",".mmmmmmm........","................","................"]},
  "blk-prose":{p:{k:"currentColor",m:"var(--ico-mid,#8A8A96)"},g:[
    "................",".kkkkkkkk.......",".kkkkkkkk.......",".kkkkkkkk.......","................","................",".mmmmmmmmmmmmmm.","................",
    ".mmmmmmmmmmmmmm.","................",".mmmmmmmmmmmmmm.","................",".mmmmmmmmm......","................","................","................"]},
  "blk-notice":{p:{k:"currentColor",y:"#F2C94C"},g:[
    "................","................",".kkkkkkkkkkkkkk.",".kyyyyyyyyyyyyk.",".kyyyyykkyyyyyk.",".kyyyyykkyyyyyk.",".kyyyyykkyyyyyk.",".kyyyyykkyyyyyk.",
    ".kyyyyykkyyyyyk.",".kyyyyyyyyyyyyk.",".kyyyyykkyyyyyk.",".kyyyyykkyyyyyk.",".kyyyyyyyyyyyyk.",".kkkkkkkkkkkkkk.","................","................"]},
  "blk-stats":{p:{a:"#3FA7E8",g:"#4FC27A",k:"currentColor",r:"#E8563B"},g:[
    "................","..........rrr...","..........rrr...","..........rrr...","......ggg.rrr...","......ggg.rrr...","......ggg.rrr...","......ggg.rrr...",
    "..aaa.ggg.rrr...","..aaa.ggg.rrr...","..aaa.ggg.rrr...","..aaa.ggg.rrr...","..aaa.ggg.rrr...","..aaa.ggg.rrr...",".kkkkkkkkkkkkkk.","................"]},
  "blk-steps":{p:{a:"#3FA7E8",k:"currentColor",m:"var(--ico-mid,#8A8A96)"},g:[
    "................",".kkkk...........",".kaak.mmmmmmmmm.",".kaak.mmmmmm....",".kkkk...........","................",".kkkk...........",".kaak.mmmmmmmmm.",
    ".kaak.mmmmmm....",".kkkk...........","................",".kkkk...........",".kaak.mmmmmmmmm.",".kaak.mmmmmm....",".kkkk...........","................"]},
  "blk-faq":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","..kkkkkkkkkkk...",".kwwwwwwwwwwwk..",".kwwwkkkkwwwwk..",".kwwkwwwwkwwwk..",".kwwwwwwwkwwwk..",".kwwwwwkkwwwwk..",".kwwwwwkwwwwwk..",
    ".kwwwwwwwwwwwk..",".kwwwwwkwwwwwk..","..kkkwkkkkkkk...","....kwk.........","....kk..........","...k............","................","................"]},
  "blk-feed":{p:{k:"currentColor",m:"var(--ico-mid,#8A8A96)",r:"#E8563B"},g:[
    "................",".kkkk.kkkkkkkkk.",".kkkk...........",".krrk.mmmmmmm...",".kkkk...........","................",".kkkk.kkkkkkkkk.",".kkkk...........",
    ".krrk.mmmmmmm...",".kkkk...........","................",".kkkk.kkkkkkkkk.",".kkkk...........",".krrk.mmmmmmm...",".kkkk...........","................"]},
  "blk-gallery":{p:{a:"#3FA7E8",g:"#4FC27A",k:"currentColor",p:"#FF5FA8",y:"#F2C94C"},g:[
    "................",".kkkkkkkkkkkkkk.",".kaaaaakkgggggk.",".kaaaaakkgggggk.",".kaaaaakkgggggk.",".kaaaaakkgggggk.",".kaaaaakkgggggk.",".kkkkkkkkkkkkkk.",
    ".kkkkkkkkkkkkkk.",".kyyyyykkpppppk.",".kyyyyykkpppppk.",".kyyyyykkpppppk.",".kyyyyykkpppppk.",".kyyyyykkpppppk.",".kkkkkkkkkkkkkk.","................"]},
  "blk-plate":{p:{a:"#3FA7E8",g:"#4FC27A",k:"currentColor",y:"#F2C94C"},g:[
    "................","................","kkkkkkkkkkkkkkkk","kaaaaaaaaaaaaaak","kaaaaaaaaaayyaak","kaaaaaaaaaayyaak","kaaaaaaaaaaaaaak","kaaaaggaaaaaaaak",
    "kaaaggggaaagaaak","kaaggggggagggaak","kaagggggggggggak","kagggggggggggggk","kggggggggggggggk","kkkkkkkkkkkkkkkk","................","................"]},
  "blk-people":{p:{a:"#3FA7E8",g:"#4FC27A",k:"currentColor",y:"#F2C94C"},g:[
    "................","................","...kkk..........","..kyyyk...kkk...","..kyyyk..kyyyk..","..kyyyk..kyyyk..","...kkk...kyyyk..","..........kkk...",
    "................",".kkkkkkk........",".kaaaaakkkkkkkk.","akaaaaakkggggggk","kaaaaaaakggggggk","kaaaaaaakgggggg.","kkkkkkkkkkkkkkkk","................"]},
  "blk-swatches":{p:{k:"currentColor",r:"#E8563B",t:"#3FD3FF",y:"#F2C94C"},g:[
    "................","................","................",".kkkk.kkkk.kkkk.",".krrk.kyyk.kttk.",".krrk.kyyk.kttk.",".krrk.kyyk.kttk.",".krrk.kyyk.kttk.",
    ".krrk.kyyk.kttk.",".krrk.kyyk.kttk.",".krrk.kyyk.kttk.",".krrk.kyyk.kttk.",".kkkk.kkkk.kkkk.","................","................","................"]},
  "blk-contact":{p:{k:"currentColor",w:"var(--ico-paper,#FFFFFF)"},g:[
    "................","................","................",".kkkkkkkkkkkkkk.",".kkwwwwwwwwwwkk.",".kwkwwwwwwwwkwk.",".kwwkkwwwwkkwwk.",".kwwwwkwwkwwwwk.",
    ".kwwwwwkkwwwwwk.",".kwwwwwwwwwwwwk.",".kwwwwwwwwwwwwk.",".kwwwwwwwwwwwwk.",".kkkkkkkkkkkkkk.","................","................","................"]}
});

// The tools the suite always had, re-inked the same way.
["t-select", "t-rect", "t-ellipse", "t-text", "t-image", "t-eyedrop", "t-pen", "t-pencil", "t-erase", "t-fill", "t-build",
  "app-swatch", "app-cutout", "app-banner", "app-type", "app-pixel", "app-layout"].forEach((id) => {
  const a = ICON_ART[id];
  if (!a) return;
  a.p = Object.assign({}, a.p);
  if (a.p.k === "#0A0A0A") a.p.k = "currentColor";
  if (a.p.w === "#FFFFFF") a.p.w = "var(--ico-paper,#FFFFFF)";
});
